CREATE USER kafka_user WITH PASSWORD "RNJ#Database"

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO kafka_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO kafka_user;
GRANT ALL PRIVILEGES ON DATABASE weather TO kafka_user;